#!/bin/bash

JSON_PATH=""
MACHINE_CONFIG_PATH=""
OUTPUTDIR=""

NARGS=$(($#-1))

for (( iarg=1; iarg<=NARGS; iarg++)); do
    jarg=$((iarg+1))

    if [ "${!iarg}" == "--json" ]
        then
            JSON_PATH=${!jarg}
    fi
    if [ "${!iarg}" == "--machine" ]
        then
            MACHINE_CONFIG_PATH=${!jarg}
    fi
    if [ "${!iarg}" == "--outputdir" ]
        then
            OUTPUTDIR=${!jarg}
    fi
done


TORUN="python3 $( dirname -- $0; )/main.py"

if [ "$JSON_PATH" == "" ]; then
    echo "Parameter is missing:"
    echo "--json: path of the requiered metadata JSON file"
    exit 1
else
    TORUN="${TORUN} --json=${JSON_PATH}"
fi

if [ "$MACHINE_CONFIG_PATH" != "" ]; then
    TORUN="${TORUN} --machine=${MACHINE_CONFIG_PATH}"
else
    echo "Machine configuration is missing"
    echo "Running script_generator without machine configuration"
fi

if [ "$OUTPUTDIR" != "" ]; then
    TORUN="${TORUN} --outputdir=${OUTPUTDIR}"
else
    echo "Output directory is missing"
    echo "Running script_generator with default output directory \".\""
fi

$TORUN