#!/bin/bash

JSON_PATH=""
MACHINE_CONFIG_PATH=""

NARGS=$(($#-1))

for (( iarg=1; iarg<=NARGS; iarg++)); do
    jarg=$((iarg+1))

    if [ "${!iarg}" == "--json" ]
        then
            JSON_PATH=${!jarg}
    fi
    if [ "${!iarg}" == "--machine" ]
        then
            MACHINE_CONFIG_PATH=${!jarg}
    fi
done

if [ "$JSON_PATH" == "" ]; then
    echo "Parameter is missing:"
    echo "--json: path of the requiered metadata JSON file"
    exit 1
else if [ "$MACHINE_CONFIG_PATH" != "" ]; then
    python3 $( dirname -- "$0"; )/main.py --json $JSON_PATH --machine $MACHINE_CONFIG_PATH
else
    echo "Machine configuration is missing"
    echo "Running script_generator without machine configuration"
    python3 $( dirname -- "$0"; )/main.py --json $JSON_PATH
fi